-- HD360 blog — esquema da Fase 2.
-- Aplicar no SQL Editor do projeto Supabase (uma vez).

create table if not exists public.posts (
  id               bigint generated by default as identity primary key,
  slug             text not null unique,
  title            text not null,
  date             timestamptz not null default now(),
  modified         timestamptz not null default now(),
  category_name    text not null,
  category_color   text not null,
  cover_image      text default '',
  excerpt          text default '',
  content          text default '',
  meta_description text default '',
  seo_title        text default '',
  og_image         text default '',
  focus_keyword    text default '',
  tags             text[] not null default '{}',
  likes            integer not null default 0,
  status           text not null default 'draft' check (status in ('draft','published')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists posts_status_idx on public.posts (status);
create index if not exists posts_date_idx on public.posts (date desc);

-- updated_at automático
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

drop trigger if exists posts_touch_updated_at on public.posts;
create trigger posts_touch_updated_at
  before update on public.posts
  for each row execute function public.touch_updated_at();

-- Curtidas: incremento anônimo seguro, sem ler/alterar mais nada.
create or replace function public.increment_likes(p_slug text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare new_count integer;
begin
  update public.posts
     set likes = likes + 1
   where slug = p_slug and status = 'published'
   returning likes into new_count;
  return coalesce(new_count, 0);
end; $$;

-- RLS
alter table public.posts enable row level security;

-- Leitura pública só de posts publicados.
drop policy if exists posts_public_read on public.posts;
create policy posts_public_read on public.posts
  for select using (status = 'published');

-- Escrita só por usuário autenticado (o admin).
drop policy if exists posts_admin_all on public.posts;
create policy posts_admin_all on public.posts
  for all to authenticated
  using (true) with check (true);

-- Permissão de execução da função de curtidas para anônimos.
grant execute on function public.increment_likes(text) to anon, authenticated;
